
import java.awt.Font;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jia
 */
public class scheduleView extends javax.swing.JFrame {

    /**
     * Creates new form scheduleView
     */
    public scheduleView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextAppointmentLbl = new javax.swing.JLabel();
        TimeTxt = new javax.swing.JTextField();
        placeTxt = new javax.swing.JTextField();
        universityTxt = new javax.swing.JTextField();
        subjectTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        nextAppointmentLbl.setText("Your Next Appointment");
        nextAppointmentLbl.setFont(new Font("Arial", Font.PLAIN, 50));
        getContentPane().add(nextAppointmentLbl);

        TimeTxt.setText("jTextField1");
        TimeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeTxtActionPerformed(evt);
            }
        });
        getContentPane().add(TimeTxt);

        placeTxt.setText("jTextField1");
        placeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeTxtActionPerformed(evt);
            }
        });
        getContentPane().add(placeTxt);

        universityTxt.setText("jTextField1");
        getContentPane().add(universityTxt);

        subjectTxt.setText("jTextField1");
        getContentPane().add(subjectTxt);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TimeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeTxtActionPerformed

    private void placeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placeTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scheduleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scheduleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scheduleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scheduleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scheduleView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TimeTxt;
    private static javax.swing.JLabel nextAppointmentLbl;
    private javax.swing.JTextField placeTxt;
    private javax.swing.JTextField subjectTxt;
    private javax.swing.JTextField universityTxt;
    // End of variables declaration//GEN-END:variables





}

